file_db = "./file_db"
save_path = "./data"
template_file = "./templates/template.docx"
xsl_file = "./style/style.xsl"
ignore_meds = ["Akut", "Basis", ":"]
fields = [
    "midas", "treatments", "symptoms", "bdi2", "whodas"
]