name = "&Symptome"

[[field]]
caption = "Häufiges Auftreten von"
id = "symptoms"
field_type = "xbox"
rows = 32
values = [
    "Kreuz- oder Rückenschmerzen",
    "Überempfindlichkeit gegen Wärme",
    "Überempfindlichkeit gegen Kälte",
    "Kurzatmigkeit",
    "Stichen, Schmerzen oder Ziehen in der Brust",
    "Kloßgefühl, Enge oder Würgen im Hals",
    "Starkem Schwitzen",
    "Schweregefühl in den Beinen",
    "Unruhe in den Beinen",
    "Nacken- oder Schulterschmerzen",
    "Schwindelgefühl",
    "Übermäßigem Schlafbedürfnis",
    "Schlaflosigkeit",
    "Kopfschmerzen, Druck im Kopf, Gesichtsschmerzen",
    "Erstickunggefühl",
    "Appetitlosigkeit",
    "Herzklopfen, Herzjagen oder Herzstolpern",
    "Verstopfung",
    "Mangel an geschlechtlicher Erregbarkeit",
    "Taubheitsgefühlen, Kribbeln, Brennen",
    "Störungen beim Wasserlassen",
    "geschwollenen Beine",
    "Blut im Stuhl",
    "anfallsweiser Atemnot",
    "Neigung zum Weinen",
    "Gelenk- oder Gliederschmerzen",
    "Mattigkeit",
    "Übelkeit",
    "Grübelei",
    "Schwächegefühl",
    "Schluckbeschwerden",
    "Leibschmerzen, Unterleibsschmerzen",
    "kalten Füße",
    "Frieren",
    "trüben Gedanken",
    "chronischem Husten",
    "Durchfall",
    "Juckreiz",
    "Reizbarkeit",
    "Zittern",
    "Druck- oder Völlegefühl im Leib",
    "Gleichgewichtsstörungen",
    "Angstgefühl",
    "Konzentrationsschwäche",
    "innerer Gespanntheit",
    "Müdigkeit",
    "Schluckauf",
    "aufsteigender Hitze, Hitzewallungen",
    "Energielosigkeit",
    "rascher Erschöpfbarkeit",
    "Heißhunger",
    "Vergesslichkeit",
    "Ohnmachtsanfällen",
    "beruflichen oder privaten Sorgen",
    "Unverträglichkeit bestimmter Speisen",
    "Regelbeschwerden",
    "Sodbrennen oder saurem Aufstoßen",
    "leichtem Erröten",
    "Gewichtsverlust",
    "starkem Durst",
    "Sehstörungen",
    "Lebensmüdigkeit",
    "Erbrechen",
    "Hautveränderungen"
]
