
# ***************
# *   CAUTION   *
# ***************

# Changes to the values in this file MUST be accompanied by changes in style.xsl

name = "&Vorbehandlungen"

[[field]]
caption = "Ärzte der Fach- bzw. Zusatzbezeichnung"
id = "treatments"
field_type = "xbox"
rows = 20
values = [
    "Akupunktur", "Allgemeinmedizin", "Apotheker", "Bademeister",
    "Chiropraktiker", "Endokrinologie", "Geistheiler", "Dermatologie",
    "Hypnotiseure", "Pädiatrie", "Pflegepersonal", "Masseure",
    "Naturheilkundler", "Neurologie", "Onkologie", "Proktologie",
    "Psychiatrie", "Psychotherapie", "Rheumatologie", "Urologie",
    "Allergologie", "Anästhesiologie", "Ophthalmologie", "Kardiologie",
    "Chirurgie", "Gynäkologie", "HNO", "Heilpraktiker",
    "Innere Medizin", "Physiotherapeuten", "Pneumologie", "MKG-Chirurgie",
    "Nervenheilkunde", "Neurochirurgie", "Orthopädie", "Priester",
    "Dipl.-Psychologe", "Radiologie", "Schmerztherapie", "Zahnheilkunde"
]
