name = "&Vorbehandlungen"

[[field]]
caption = "Ärzte der Fach- bzw. Zusatzbezeichnung"
id = "treatments"
field_type = "xbox"
rows = 20
values = [
    "Akupunktur", "Allgemeinarzt", "Apotheker", "Bademeister",
    "Chiropraktiker", "Endokrinologe", "Geistheiler", "Hautarzt",
    "Hypnotiseur", "Kinderarzt", "Pflegekraft", "Masseur",
    "Naturheilkundler", "Neurologe", "Onkologe", "Proktologe",
    "Psychiater", "Psychotherapeut", "Rheumatologe", "Urologe",
    "Allergologe", "Anästhesiologe", "Augenarzt", "Kardiologe",
    "Chirurg", "Frauenarzt", "HNO-Arzt", "Heilpraktiker",
    "Internist", "Physiotherapeut", "Lungenarzt", "MKG-Chirurg",
    "Nervenarzt", "Neurochirurg", "Orthopäde", "Priester",
    "Dipl.-Psychologe", "Radiologe", "Schmerztherapeut", "Zahnarzt"
]