name = "&WHODAS 2.0"

[[field]]
caption = "Betroffene Lebensbereiche"
id = "sections"
field_type = "xbox"
values = [
    "Verständnis und Kommunikation",
    "Mobilität",
    "Selbstversorgung",
    "Umgang mit anderen Menschen",
    "Tägliches Leben",
    "Teilnahme am gesellschaftlichen Leben"
]

[[field]]
caption = "Score"
id = "whodas"
field_type = "split_line"
max_entries = 3